version: '3.8'

services:
  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS port

    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/redirect.conf:/etc/nginx/conf.d/redirect.conf
      - /etc/letsencrypt/live/trailrove.com/fullchain.pem:/etc/ssl/certs/trailrove.com.crt
      - /etc/letsencrypt/live/trailrove.com/privkey.pem:/etc/ssl/private/trailrove.com.key
    depends_on:
      - php
    networks:
      - laravel

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  # MySQL Service
  database:
    image: mysql:8.0.25
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # phpMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: database
    ports:
      - "8888:80"
    depends_on:
      - database
    networks:
      - laravel

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --requirepass "your_redis_password"
    volumes:
      - redisdata:/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  redisdata:
