version: '3.1'

networks:
  laravel:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - laravel

  pma:
    image: phpmyadmin:5.1
    container_name: pma
    environment:
      PMA_HOST: database
    depends_on:
      - database
    ports:
      - 8888:80
    networks:
      - laravel

  database:
    image: mysql:8.0.25
    container_name: database
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    networks:
      - laravel

  php:
    build:
      args:
        user: parham
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    links:
      - database
    depends_on:
      - redis
      - database
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: library/composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: library/node:14.15.4
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  redis:
    image: "redis:latest"
    container_name: redis
    restart: on-failure
    command: redis-server --appendonly yes --requirepass "parham"
    ports:
      - "63799:6379"
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - laravel

volumes:
  dbdata: